# Generated by Django 4.2.5 on 2023-10-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='categorie',
            new_name='categories',
        ),
    ]
