# Generated by Django 4.2.5 on 2023-10-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_categorie_bg_color_alter_transaction_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='bg_color',
            new_name='couleur',
        ),
    ]
