# Generated by Django 4.2.6 on 2023-10-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_bg_color_categorie_couleur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('date', 'nom', 'montant')},
        ),
    ]
